# Generated by Django 5.2.4 on 2025-07-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='recepie_image',
            field=models.ImageField(upload_to='recepie_img'),
        ),
    ]
